name: Lint (pre-commit)

# default token permissions: none
permissions: {}

on:
  pull_request:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Install Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: v1.22.x
          cache: true
      - run: go run mage.go lint
